- name: Restart {{ cookiecutter.app_name_slug }} service
  ansible.builtin.systemd:
    name: {{ cookiecutter.app_name_slug }}
    state: restarted
    daemon_reload: true
  when: not {{ cookiecutter.app_name_ansible_var }}_service_started.changed
